version: '3.8'

services:
  birthday-bot:
    build: .
    container_name: birthday_bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./images:/app/images
    env_file:
      - .env