version: '3.8'

services:
  birthday-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: birthday_bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./images:/app/images
    environment:
      TOKEN: "${TOKEN}"


